#
# Copyright (c) 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file contains an OpenShift template that creates all the objects needed
# for a working development installation of the events management service.

apiVersion: v1
kind: Template
metadata:
  name: secrets
parameters:

- name: DB_HOST
  description: Database host name.

- name: DB_PORT
  description: Database port number.

- name: DB_NAME
  description: Database name.

- name: DB_USER
  description: Database user name.

- name: DB_PASSWORD
  description: Database password.

- name: DB_ADMIN_USER
  description: Database administrator user.

- name: DB_ADMIN_PASSWORD
  description: Database administrator password.

- name: CLIENT_ID
  description: Identifier for the OpenID client.

- name: CLIENT_SECRET
  description: Secret for the OpenID client.

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: events-mgmt-db
  stringData:
    db.host: ${DB_HOST}
    db.port: ${DB_PORT}
    db.name: ${DB_NAME}
    db.user: ${DB_USER}
    db.password: ${DB_PASSWORD}

- apiVersion: v1
  kind: Secret
  metadata:
    name: events-mgmt-db-admin
  stringData:
    db.host: ${DB_HOST}
    db.port: ${DB_PORT}
    db.name: ${DB_NAME}
    db.user: ${DB_ADMIN_USER}
    db.password: ${DB_ADMIN_PASSWORD}

- apiVersion: v1
  kind: Secret
  metadata:
    name: events-mgmt-server
  stringData:
    client.id: ${CLIENT_ID}
    client.secret: ${CLIENT_SECRET}
